### ISSUE TITLE
Features missing

### ISSUE THREAD

**Issue by Karluzo** [SqlQuantumLeap/SimpleSqlExec#1]
I will try to write here the features that would be useful from my point of view:

1) Connecting to a running instance should be most simple, I would say writing instance name should be enough, or it can connect automatically to the only instance, that is running
2) Support for SELECT queries should be added
3) Should provide rows affected info for queries with NOCOUNT OFF
4) Better query error handling
5) Allow execute more statements using command prompt  (not just command line parameter)
6) Perhaps a simple password protection against meddling of inexperienced users

**Comment by SqlQuantumLeap** [comment]
I am not sure about #1. Is prefixing an instance name with "(localdb)\" that much of a burden? If so, maybe a specific command-line parameter for a LocalDB Instance would suffice and it would handle the prefix?

Yes to #2, #3, and #4.

I do not understand #5.

I do not see the use in #6. What meddling can someone do? Where would the password be stored that such a user couldn't get it? What would it protect against that they couldn't get around by installing some other query tool?

**Comment by Karluzo** [comment]
By 5 I mean when I want to do one select to see the the data, then one update to change it and then one select to see, if it was really changed well, I do not want to write allways the whole command "SimpleSqlExec -connection '(localdb)\MsSqlServer'  -command 'SELECT x.Id FROM x WHERE x.y=5'". It may be matter of personal preferences. When I update something I usually run a sequence of SELECT / BEGIN TRAN / UPDATE / SELECT / ROLLBACK TRAN / SELECT command to safely see, if the sql code does really what it is supposed to do in the production database.

**Comment by SqlQuantumLeap** [comment]
I am still not entirely sure what you mean by #5. It sounds like you are thinking that this only runs one query at a time. Is that correct? If so, then maybe I was unclear in the beginning. This runs a single `SqlCommand`, which represents an entire batch of T-SQL queries. Batches are normally separated by `GO` in SQLCMD and SSMS. But the UPDATE and SELECT and ROLLBACK within a Transaction will work in **SimpleSqlExec** as of right now, even without handling multiple batches. Just don't put in any `GO` separators :-). Also, you don't need a separate SELECT to check the UPDATE. Just use the OUTPUT clause :-).

PS. I have quite a bit more done, but so far it is in the other branch. I am hoping to finish the rest of the output handling tomorrow. But as of right now, it does handle getting back 1 _or more_ result sets and will display them or send them to an output file.

**Comment by Karluzo** [comment]
Tried the current version I could not figure how to use it, tried

SimpleSqlExec.exe -cs "Data Source=(localdb)\ESift;Integrated Security=true" -Q "SELECT \* FROM TypAkce"
SimpleSqlExec.exe -cs "Data Source=(localdb)\MsSqlServer;Initial Catalog=ESift;Integrated Security=true" -Q "SELECT \* FROM TypAkce"
SimpleSqlExec.exe -cs "Server=np:\.\pipe\LOCALDB#B97A46D1\tsql\query;Initial Catalog=ESift;Integrated Security=true" -Q "SELECT \* FROM TypAkce"

But allways it does just nothing, no error message, no output, only pressing Ctrl+C breaks the program.

**Comment by SqlQuantumLeap** [comment]
That is strange. It works quite well for me. I have tested against SQL Server 2012 Developer Edition and Express LocalDB. The first time I connected to LocalDB I got a timeout error since LocalDB was starting. But after that it was just fine.

How long did you wait before hitting Control-C? Can you run it without any switches to see if you get the Usage displayed?

I started making a test CMD script that runs it in many different ways. I will upload that tomorrow.

**Comment by Karluzo** [comment]
It works without args. The LocalDB instance was already running so it seemed to me that I have entered some wrong params or something like that.

**Comment by SqlQuantumLeap** [comment]
That is odd. I ran it on another computer and it worked just fine. I copied and pasted your first example line `SimpleSqlExec.exe -cs "Data Source=(localdb)\ESift;Integrated Security=true" -Q "SELECT * FROM TypAkce"` and edited just the instance name of the LocalDB and changed the table name to be `sys.objects`, and it returned a result set. Have you tried the latest version, 1.0.3. ?

**Comment by SqlQuantumLeap** [comment]
Hi. Have you tried one of the more recent builds? I am almost done with what will be v 1.0. All that is left is adding the ability to parse multiple batches, typically separated by `GO` statements. I already have that code in another project so I will have that worked in tomorrow. But I have done quite a bit of testing and so far it is working nicely. I have added the test script to the "Compiled" folder. It is currently geared towards working on a system with a default instance, which won't work if you only have LocalDB. But that is easy to fix and I will have that updated tomorrow as well.

From the original request list at the topic of this issue:
- 2 and 3 are done.
- 4 is difficult to determine since "better" is subjective. The code is definitely "better" with error handling than in the first build. Much better. However, I have not implemented the `-m error_level` and `-V error_severity_level` switches that are available in SQLCMD. But I am also not sure how important those two switches are.
- 5 I am still not 100% sure I understand, but if it means running multiple statements in a single batch (i.e. _not_ separate by any `GO` statements), then that was available since the first build. If it means sets of statements that _are_ separated by `GO` statements, then that will be available tomorrow.

**Comment by SqlQuantumLeap** [comment]
I believe this is all done. For #1, if we are not being specific to LocalDB, then Version 1 already handles connecting to a local, default instance using integrated security by default, without the need to specify anything. This mirrors the behavior of SQLCMD. Both SQLCMD and SimpleSqlExec can run with only specifying either `-Q` or `-i`.

I am going to close this out so that I can release v 1.0.
